default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['FOGSYNC_BACKEND_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: fogsync_backend_development

test:
  <<: *default
  database: fogsync_backend_test

production:
  <<: *default
  database: fogsync_backend_production
  url: <%= ENV['DATABASE_URL'] %>
